# -*- coding: utf-8 -*-
"""Python On Google Sheets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_IzvlV1nLgMZDbZuojOkOqJaaSNots3

# Saving data to Google Sheets


This snippet uses the open-source [gspread](https://github.com/burnash/gspread) library for interacting with Sheets.
"""

from google.oauth2 import service_account
from google.auth.transport.requests import Request
import google.auth
import gspread
# Load the service account key file (replace 'path/to/your-key.json' with your file path)
"""
Go to https://developers.google.com/workspace/guides/create-credentials#service-account
1. create a service account and download the json file
2. Add API_KEY to download the .json file
3. Then add the service account email to the spreadsheet or google drive folder where you want to authorize access
"""

credentials = service_account.Credentials.from_service_account_file(
    'credentials/pythondatascience_serviceaccount.json',
    scopes=['https://www.googleapis.com/auth/drive']
)

gc = gspread.authorize(credentials)

# sh = gc.create('A new spreadsheet')

# # Open our new sheet and add some data.
# worksheet = gc.open('A new spreadsheet').sheet1

# cell_list = worksheet.range('A1:C2')

# import random
# for cell in cell_list:
#   cell.value = random.randint(1, 10)

# worksheet.update_cells(cell_list)
# # Go to https://sheets.google.com to see your new spreadsheet.

"""# Importing data from Google Sheets"""


worksheet = gc.open_by_key('14FetNniwjXfGuO3vqnQ0PZhh3ldCH7YlHXCbWXUfxyQ').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
#print(rows)

# Convert to a DataFrame and render.
import pandas as pd
df = pd.DataFrame.from_records(rows)

"""**Now, let's analyze**"""

print(df.head(3))

print(df.describe())